# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v1
    - name: Test
      run: |
        mvn clean test
    #- name: Process allure report
    #  if: always()
    #  run: |
    #    cd ixo && ./gradlew allureReport
    #    zip allure-report.zip -r build/reports/allure-report
    - name: Generate report
      if: always()
      run: |
        mvn allure:report
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-reports/
